### ISSUE TITLE
Image galleries

### ISSUE THREAD

**Issue by dorthrithil** [LocalCrag/LocalCragApp#15]
> Galeriefunktion auf Gebiets-/Sektor-/Bereichs-/Boulderebene. Man läd ein Foto direkt auf der jeweiligen Ebene hoch und es gilt für diese und alle darüber befindlichen und wird dort in der jeweiligen Galerie gelistet. Also jedes Bild bei Windei wird gelistet bei Romani und Glees.

**Comment by PeterGrabowitz** [comment]
Allow for users to upload photos and submit video links with the according tags. Photo/Video Link has to be released by admin.

**Comment by dorthrithil** [comment]
Followup: masonry layout
