### ISSUE TITLE
New entries overview

### ISSUE THREAD

**Issue by dorthrithil** [LocalCrag/LocalCragApp#151]
Add an overview that lists relevant changes to elements:

- [ ] Grade change
- [ ] New line added
- [ ] New crag / sector / area added

Todos:

- [x] Check that alembic notices schema changes of history tables
- [x] Set current user flask var to get it to correctly auto populate the field in the history tables
- [ ] current_user_id_factory loads user second time in some requests - handle this
- [ ] delete history elements of deleted elements

**Comment by dorthrithil** [comment]
@PeterGrabowitz What do you think about the three points listed here? I think upgrades / downgrades could also be relevant for people. 

For the case "new crag ..." I would only list the added crag and not all lines in it, if we decide to publish a new one. E.g. for Kopf it would be massive spam to this list if we publish the crag and 40 items are listed. I am planning a "draft" feature for crags etc, so the "New entry" listing could be triggered by publishing a crag for the first time.

**Comment by PeterGrabowitz** [comment]
Up-/Downgrades would be interesting, yeah. Maybe have the system check each newly added ascent for whether someone chose a different grade from the established one. 

I agree that listing all items of a newly added crag/sector is "spam". If not too much work an idea could be to have the entry contain the number of  lines that the new crag/sector contains. 

What about the (most regularl case) of a new area? I would list both here, the new area and all lines. That is basically the main business of development: establishing a new area.

**Comment by dorthrithil** [comment]
So I tried implementing this using the fancy full blown continuum way but was struggeling at many places getting it to work properly. Specifically some lifecycle issues where the version models were't showing the correct changes yet I have to act upon to implement this feature. 
As actually a complete version history of all changes is a lot of overhead, I am not switching to the simple version without library but with a little more manual setup which in turn gives 100% control over what is happening.
