### ISSUE TITLE
Tick lists

### ISSUE THREAD

**Issue by dorthrithil** [LocalCrag/LocalCragApp#16]
Features:

- [x] Configure cascade accordingly - ticks should delete on user delete
- [x] Total ascent count should be property of line and work without querying ascends
- [x] Plan for fast crag/sector/... ascent list loading - extra FK's needed?
- [x] Add "Add ascent" buttons in line detail view and line list views
- [x] Show "Add ascents" buttons in green / ticked for ticked lines
- [x] Add navigation targets for lines etc in ascent lists
- [x] Add user tick lists
- [x] Add edit buttons ascent lists for own ascents
- [x] Add edit feature
- [x] Add delete feature in edit form
- [x] Prevent ticking more then once?

Tests:

- [x] Server Tests for adding ascents
- [x] Server Tests for updating ascents
- [x] Server Test for ascent list
- [x] Server Test for tick list
- [x] Server Test for deleting ascent
- [x] Test that deleting tick doesn't cascade on line
- [x] Test that deleting user deletes ascent but not line
- [x] E2E Test for complete ascent workflow: Create -> Show list -> Edit -> Delete

**Comment by PeterGrabowitz** [comment]
- Maybe allow for some "multi tick" option with the view of a sector spot (Bereich) if not too much work. Would not only be relevant for starting a scorecard and adding older ascents but quite regularly also after a normal crag visit when you´ve done 10 or more lines. Possible solution: When clicking "Linien ticken" from that view, the display changes to the following one: 
![image](https://github.com/LocalCrag/LocalCragApp/assets/103489392/b4e8c55b-b412-4ef8-b494-67bd12e570fc)

- Allow for ticking boulders from the line view, the topo picture view and the specific line view. 

- Allow for ticking flashs, but don´t count them differently pointwise for the rankings

- Allow for not providing a date for an ascent or only providing a year. Allow for specific days for personal log keeping but don´t really use them in statistics unless necessary.

**Comment by dorthrithil** [comment]
1. I won't do multi-tick for now. Mainly because of the work overload compared to the use. It's only a real usecase for our few users where we have to tick a few hundred lines all at once. Later on it's fine to just click like 1-10 times, depending on your session. I also want to add a comment function in the ticking process which will be hard ux-wise when looking at multi tick functionality.
2. Yes, this will be possible form everywhere
3. Jep
4. Yes, I want to provide the options "year", "date" and "None" for the date.

**Comment by dorthrithil** [comment]
I also plan to add an "FA" field. When this is filled, the FA info in the line model is overridden and the user detail page can be clicked on the name etc.

**Comment by PeterGrabowitz** [comment]
Great!

A remark regarding use case of multi tick: Not sure whether this isn´t actually a pretty common case for any instance. Most users in the Eifel will have done lots of stuff before, same is true for any other instance created for a different region. It might be a not to trivial obstacle in adopting the scorecard  by users. That was my idea behind it and not mainly to easy the workload for "us".
