### ISSUE TITLE
Add feature to claim project ticks

### ISSUE THREAD

**Issue by dorthrithil** [LocalCrag/LocalCragApp#249]
Instead of the ticklist box button, for projects I think we can have a button that opens your email program. There can be some prefilled questions about the ascend:

- When did you climb it?
- How did you name it?
- How did you grade it?
- How would you rate it?
- Do you have a video? Ideally send the uncompressed video e.g. via wetransfer or provide a link to the video.
- Is the drawn line in the topo drawn correctly or does your climbed line differ in places?

We will add the line in the topo, you can tick it afterwards with your user, if you like.

I prefer a simple email above some complicated feature for automatically converting projects via a FA tick to a complete line. Simply because it will not happen very often. Thoughts @PeterGrabowitz ?

**Comment by PeterGrabowitz** [comment]
I agree, especially for any kind of "initial" phase (years), there is no need for anything going beyond that. And convmerting a report into data on the site is super easy now anyways.
