### ISSUE TITLE
Images not loading on iOS

### ISSUE THREAD

**Issue by dorthrithil** [LocalCrag/LocalCragApp#397]
Sometimes this happens:

![WhatsApp Image 2024-06-19 at 11 06 44 (1)](https://github.com/LocalCrag/LocalCragApp/assets/3655915/5d9cddf4-6a36-4419-8381-bccc35cdca00)
![WhatsApp Image 2024-06-19 at 11 06 44](https://github.com/LocalCrag/LocalCragApp/assets/3655915/96acd621-8dfc-422b-ae17-0b648f26b309)

It's a but unclear, but it appears to be happening after logging a line.

**Comment by dorthrithil** [comment]
@BlobbyBob Do you by chance have an iPhone and can reproduce this? A friend reported this, but I cannot reproduce it on Android.

**Comment by BlobbyBob** [comment]
No, unfortunately not. But for another project a friend of mine used [BrowserStack](https://www.browserstack.com/open-source?ref=pricing) for stuff like that. Their service is free for open-source projects, so maybe take a look at that.

**Comment by dorthrithil** [comment]
Tried Browserstack, thanks for the hint. However I couldn't reproduce the issue there, the images were showing up as expected. The friend who reported the bug is the only user who reported this - and there it only happens sometimes. He also didn't complain again since months. So I'll just close this for now until we get more reports of the issue.
