### ISSUE TITLE
Login page stuck in infinite loop when already logged in

### ISSUE THREAD

**Issue by BlobbyBob** [LocalCrag/LocalCragApp#459]
Opening the login page (e.g. on [gleesbouldering](https://www.gleesbouldering.com/login)) works fine, when not logged in. However, when a session is active the page stays blank because some frontend script is stuck in an infinite loop. Force-stopping the script shows [is-logged-out.ts:27](https://github.com/LocalCrag/LocalCragApp/blob/main/client/src/app/guards/is-logged-out.ts#L27) to somehow be involved.

OS: Linux  
Browser: Firefox 130.0.1

**Comment by dorthrithil** [comment]
Thanks again for reporting, added this to the current Milestone. This should be an easy fix. 
If you're interested, I would also be happy about Pull requests for this and other issues. :) 
Do we maybe know each other from the crag by chance?

**Comment by BlobbyBob** [comment]
> Thanks again for reporting

You're welcome :smile: 

> If you're interested, I would also be happy about Pull requests for this and other issues. :)

I've been into Vue in the past, but tried to avoid Angular the best I could :sweat_smile:
If I find enough time and good fitting issues, I will definitely contribute some PRs, but I think an issue like this is much more time-efficient for you to fix than for me. But of course there are also backend issues which I could fix while successfully keeping my Angular-avoidance streak :D


> Do we maybe know each other from the crag by chance?

I don't think so. We might have walked past each other some time, but I don't think we have had any interactions yet :)

**Comment by dorthrithil** [comment]
> I've been into Vue in the past, but tried to avoid Angular the best I could 😅
If I find enough time and good fitting issues, I will definitely contribute some PRs, but I think an issue like this is much more time-efficient for you to fix than for me. But of course there are also backend issues which I could fix while successfully keeping my Angular-avoidance streak :D

Haha, so your plan to commit yourself to the gym usage feature doesn't sound very Angular-avoiding to me. Welcome to the dark side! :D

> I don't think so. We might have walked past each other some time, but I don't think we have had any interactions yet :)

Ahh ok. I was talking to some dev guy in the crag on Sunday about this project. Thought it might have been you. But apparently not. :D

**Comment by dorthrithil** [comment]
Fixed here: https://github.com/LocalCrag/LocalCragApp/pull/454/commits/15937c909e15db90a4ac76688f21e663c0ee57f6

Copy paste error from the logged in guard...
