### ISSUE TITLE
FRONTEND_HOST leads to ugly action_links in mails

### ISSUE THREAD

**Issue by BlobbyBob** [LocalCrag/LocalCragApp#460]
At least on gleesbouldering.com, all `action_link`s in mails are derived from the `FRONTEND_HOST` configuration, which leads to ugly links as its value is set to the full Digitalocean deployment. 
It would be nice to have hostnames matching the website you are registering on.

However, I'm not sure whether this is a misconfigured deployment or a real localcrag issue (or missing alias feature).

**Comment by dorthrithil** [comment]
Thanks for reporting! Just fixed it, it was indeed an old env var value in the Digitalocean deployment I forgot to replace after I connected the domain..
