### ISSUE TITLE
Add contributors to Readme

### ISSUE THREAD

**Issue by dorthrithil** [LocalCrag/LocalCragApp#469]
https://stackoverflow.com/questions/68025091/add-github-accounts-to-readme-file

**Comment by dorthrithil** [comment]
@BlobbyBob FYI the contributors section in the readme is now live, but for some reason it doesn't show you. Maybe some caching issue of contrib.rocks. Let's wait some more days, if it doesn't update I'll use another solution. Would be nice to have every avatar on there :)

**Comment by BlobbyBob** [comment]
Yeah, I already saw that :D
contrib.rocks also does not offer an option to update the cache, but as I'm listed in GitHub's contributor page, it will probably only be a matter of time
