### ISSUE TITLE
Sektorbeschreibung editieren

### ISSUE THREAD

**Issue by PeterGrabowitz** [LocalCrag/LocalCragApp#70]
Die aktuellen Inhalte der Beschreibung eines Sektors auf der Sektorsübersichtsseite werden nicht  angezeigt, wenn man auf edit geht, weder Text noch Bild, nur der Name.

![image](https://github.com/LocalCrag/LocalCragApp/assets/103489392/be76d9d8-c1b4-4f2a-a398-c8c816f7d197)
![image](https://github.com/LocalCrag/LocalCragApp/assets/103489392/48254bfb-100a-4e41-8fca-b0249ce00a3b)

**Comment by dorthrithil** [comment]
Ist im Feature branch mit den Linienverläufen gefixt
