### ISSUE TITLE
Mobile optimisations for 1.0.0

### ISSUE THREAD

**Issue by dorthrithil** [LocalCrag/LocalCragApp#79]
Check if everything works on mobile. There is definetely some stuff to fix!

- [x] Add option to "hover" lines on mobile devices for highlighting
- [x] The "rules" box doesn´t scale at all on devices/browsers.
- [x] Bucket grades in bar charts if on mobile
- [x] Buttons overflow everywhere
- [x] Line editor doesnt listen to touch events
- [x] Fix scroll on back navigation
- [x] Fix topo image scaling on screen size changes
- [x] Fix breadcrumb overflow
- [x] Check forms

**Comment by PeterGrabowitz** [comment]
The "rules" box doesn´t scale at all on devices/browsers.

**Comment by dorthrithil** [comment]
" Add option to "hover" lines on mobile devices for highlighting"

This is impossible because there is no such thing as hover on touch devices and the only option would be to add another click target to the lists just for highlighing - but there is no space for this.

**Comment by PeterGrabowitz** [comment]
First click highlights the line, second click opens the line´s site? Can be confusing?

**Comment by PeterGrabowitz** [comment]
A solide alternative would be if once you´ve clicked on a specific boulder to look at see only its line and then click "back" you see the same top picture you´ve clicked the boulder at and don´t jump back to the top of the topo picture overview. Annoying to navigate then when looking at multiple boulders in detail.

**Comment by dorthrithil** [comment]
> First click highlights the line, second click opens the line´s site? Can be confusing?

This would be too confusing, yes

**Comment by dorthrithil** [comment]
> A solide alternative would be if once you´ve clicked on a specific boulder to look at see only its line and then click "back" you see the same top picture you´ve clicked the boulder at and don´t jump back to the top of the topo picture overview. Annoying to navigate right now when looking at multiple boulders in detail.

This sounds like a must improvement. I noticed that myself yesterday when adding the Autobahn images etc

**Comment by dorthrithil** [comment]
Scroll position restoration for the topo image list is implemented now in this branch
