### ISSUE TITLE
Arrow editor not working in Brave

### ISSUE THREAD

**Issue by dorthrithil** [LocalCrag/LocalCragApp#83]

**Comment by dorthrithil** [comment]
Bei mir klappt es in Brave @PeterGrabowitz 

Bitte probier nochmal, und wenns weiter nicht klappt bräuchte ich die Konsolenausgaben im Browser.

**Comment by dorthrithil** [comment]
OK, hab doch einen case gefunden wo er nicht klappt. Seltsam..

**Comment by dorthrithil** [comment]
OK, habs gefunden. Brave ist Schuld, lässt sich nur von Brave fixen: https://community.brave.com/t/brave-shield-breaking-konva-a-common-javascript-library-for-drawing-canvas-graphics/508071

Dieses fingerprint shield deaktivieren funktioniert. Danach klappt alles.

**Comment by PeterGrabowitz** [comment]
Alles klar, danke
